.TH "D:/Magnus/Magnus/Classes/AboutScene.h" 3 "Sat May 3 2014" "Version 0.1" "Magnus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Magnus/Magnus/Classes/AboutScene.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'cocos2d\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAboutScene\fP"
.br
.RI "\fIWindow where we will explain the game and a bit of ourselves\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Magnus from the source code\&.
