.TH "D:/Magnus/Magnus/Classes/AppDelegate.h" 3 "Sat May 3 2014" "Version 0.1" "Magnus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Magnus/Magnus/Classes/AppDelegate.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'cocos2d\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAppDelegate\fP"
.br
.RI "\fIThe cocos2d Application, this is the man behind the curtain, Magnus\&.\&.? =) \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Magnus from the source code\&.
