.TH "LevelSelectScene" 3 "Sat May 3 2014" "Version 0.1" "Magnus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LevelSelectScene \- 
.PP
This the window where you load or select the level you want to play, this unlocks as you advance through the story/game\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <LevelSelectScene\&.h>\fP
.PP
Inherits Layer\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual bool \fBinit\fP ()"
.br
.RI "\fIThe Load Game Scene is prepared and created if everything goes fine\&. \fP"
.ti -1c
.RI "void \fBreturnGameMenu\fP (cocos2d::Ref *pSender)"
.br
.RI "\fISe invoca cuando el jugador presiona el boton 'regresar al inicio'\&. \fP"
.ti -1c
.RI "\fBCREATE_FUNC\fP (\fBLevelSelectScene\fP)"
.br
.RI "\fIWe create a function, basically we will do a layer above the background, this will allow us to use it\&. \fP"
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static cocos2d::Scene * \fBcreateScene\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
This the window where you load or select the level you want to play, this unlocks as you advance through the story/game\&. 
.SH "Member Function Documentation"
.PP 
.SS "LevelSelectScene::CREATE_FUNC (\fBLevelSelectScene\fP)"

.PP
We create a function, basically we will do a layer above the background, this will allow us to use it\&. 
.PP
\fBParameters:\fP
.RS 4
\fIWe\fP need the class type to create the layer\&. 
.RE
.PP

.SS "Scene * LevelSelectScene::createScene ()\fC [static]\fP"

.SS "bool LevelSelectScene::init ()\fC [virtual]\fP"

.PP
The Load Game Scene is prepared and created if everything goes fine\&. 
.PP
\fBReturns:\fP
.RS 4
true Initialize success, program continues\&. 
.PP
false Initialize failed, program terminates\&. 
.RE
.PP

.SS "void LevelSelectScene::returnGameMenu (cocos2d::Ref *pSender)"

.PP
Se invoca cuando el jugador presiona el boton 'regresar al inicio'\&. If the logo is clicked then we return to the Game Menu 
.PP
\fBParameters:\fP
.RS 4
\fIWe\fP require the reference of the game menu 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Magnus from the source code\&.
