.TH "D:/Magnus/Magnus/Classes/LevelSelectScene.h" 3 "Sat May 3 2014" "Version 0.1" "Magnus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Magnus/Magnus/Classes/LevelSelectScene.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'cocos2d\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLevelSelectScene\fP"
.br
.RI "\fIThis the window where you load or select the level you want to play, this unlocks as you advance through the story/game\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Magnus from the source code\&.
