.TH "D:/Magnus/Magnus/Classes/MenuInicio.h" 3 "Sat May 3 2014" "Version 0.1" "Magnus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Magnus/Magnus/Classes/MenuInicio.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'cocos2d\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMenuInicio\fP"
.br
.RI "\fIThe is the main menu class, here you can choose to play a new game, load a previous one, modify options, check the about window or your achievements and exit\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Magnus from the source code\&.
