.TH "OptionsScene" 3 "Sat May 3 2014" "Version 0.1" "Magnus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OptionsScene \- 
.PP
Here you modify the options so you can enjoy more the game\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <OptionsScene\&.h>\fP
.PP
Inherits Layer\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual bool \fBinit\fP ()"
.br
.RI "\fIOptions Scene is prepared and created/displayed if everything goes fine\&. \fP"
.ti -1c
.RI "void \fBreturnGameMenu\fP (cocos2d::Ref *pSender)"
.br
.RI "\fIWe call this when the player hit the 'regresar al inicio', what it does is return to the front, the menu\&. \fP"
.ti -1c
.RI "\fBCREATE_FUNC\fP (\fBOptionsScene\fP)"
.br
.RI "\fIWe create a function, basically we will do a layer above the background, this will allow us to use it\&. \fP"
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static cocos2d::Scene * \fBcreateScene\fP ()"
.br
.RI "\fIWe prepare our scene\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Here you modify the options so you can enjoy more the game\&. 
.SH "Member Function Documentation"
.PP 
.SS "OptionsScene::CREATE_FUNC (\fBOptionsScene\fP)"

.PP
We create a function, basically we will do a layer above the background, this will allow us to use it\&. 
.PP
\fBParameters:\fP
.RS 4
\fIclass\fP type We need the class type to create the layer\&. 
.RE
.PP

.SS "Scene * OptionsScene::createScene ()\fC [static]\fP"

.PP
We prepare our scene\&. 
.PP
\fBReturns:\fP
.RS 4
instance pointer We return the id (Identification) 
.RE
.PP

.SS "bool OptionsScene::init ()\fC [virtual]\fP"

.PP
Options Scene is prepared and created/displayed if everything goes fine\&. 
.PP
\fBReturns:\fP
.RS 4
true Initialize success, program continues\&. 
.PP
false Initialize failed, program terminates\&. 
.RE
.PP

.SS "void OptionsScene::returnGameMenu (cocos2d::Ref *pSender)"

.PP
We call this when the player hit the 'regresar al inicio', what it does is return to the front, the menu\&. If the logo is clicked then we return to the Game Menu 
.PP
\fBParameters:\fP
.RS 4
\fIreference\fP We require the reference of the game menu 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Magnus from the source code\&.
