.TH "D:/Magnus/Magnus/Classes/OptionsScene.h" 3 "Sat May 3 2014" "Version 0.1" "Magnus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Magnus/Magnus/Classes/OptionsScene.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'cocos2d\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBOptionsScene\fP"
.br
.RI "\fIThe reason for implement as private inheritance is to hide some interface call by Director\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Magnus from the source code\&.
